[package]
name = "chat-app-try1"
version = "0.1.0"
edition = "2021"
publish = false

[lib]

[dependencies]
shuttle-service = { version = "0.11.0", features = ["web-axum"] }
axum = "0.6.10"
sync_wrapper = "0.1.2"
